### ISSUE TITLE
关于批量扫描的问题

### ISSUE THREAD

**Issue by kevien** [brianwrf/hackUtils#1]
能否添加个扫描例如1.1.1.1/24 这样的功能  -XD

**Comment by brianwrf** [comment]
你是指针对某些专门的漏洞在批量的时候可以使用CIDR格式的IP扫描是吗？

**Comment by kevien** [comment]
嗯 ，已经搞定了  用了一个第三方的库

**Comment by kevien** [comment]
现在在想弄成多线程的扫描。。。^_^

**Comment by brianwrf** [comment]
Good to hear:) 欢迎为这个开源小工具添砖加瓦，我可以给你开个分支
