### ISSUE TITLE
struts2-032rce how to execute system command?

### ISSUE THREAD

**Issue by loveyou789** [brianwrf/hackUtils#2]
nice script,but i have a question:
struts2-032rce module,how to execute system command after webshell upload successful?
like this, http://www.example.com/webshell.jsp?shellpwd=xxx&t=[command], and the OS is windows,then I execute command "whoami" or "ipconifg",but nothing output...

**Comment by brianwrf** [comment]
The script has been updated, please git clone and run it again. The webshell format like this: http://www.example.com/nimabi.jsp?pwd=nmb&cmd=[command]. Feel free to ask if you have any issues about this script.

**Comment by loveyou789** [comment]
yeah,thanks a lot...

Best Regards!
Ben Lee


Date: Mon, 9 May 2016 05:02:33 -0700
