### ISSUE TITLE
not work for me 

### ISSUE THREAD

**Issue by lacroutelacroute** [brianwrf/hackUtils#4]
thsi soft not work for me
install from scratch
:/opt/hackUtils/hackUtils$ sudo python ./hackUtils.py 
Traceback (most recent call last):
  File "./hackUtils.py", line 28, in <module>
    from bs4 import BeautifulSoup
  File "/opt/hackUtils/hackUtils/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/opt/hackUtils/hackUtils/bs4/builder/__init__.py", line 311, in <module>
    from . import _html5lib
  File "/opt/hackUtils/hackUtils/bs4/builder/_html5lib.py", line 57, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

**Comment by brianwrf** [comment]
Hey,

Please follow below steps to try it again:
1. git clone https://github.com/brianwrf/hackUtils
2. cd hackUtils
3. python hackUtils.py -h

For any question, please let me know.

Thanks,

**Comment by brianwrf** [comment]
Also, you can refer to below link to install it.

[http://seclist.us/hackutils-a-python-script-for-hacking-toolkit-penetration-test-and-web-security-research.html](url)

**Comment by lacroutelacroute** [comment]
after deleted lib python and reinstall from scratch
and look url

not work for me

$ sudo python ./hackUtils.py -h
Traceback (most recent call last):
  File "./hackUtils.py", line 28, in <module>
    from bs4 import BeautifulSoup
  File "/opt/hackUtils/hackUtils/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/opt/hackUtils/hackUtils/bs4/builder/__init__.py", line 311, in
<module>
    from . import _html5lib
  File "/opt/hackUtils/hackUtils/bs4/builder/_html5lib.py", line 57, in
<module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'


2016-11-25 6:16 GMT+01:00 brianwrf <notifications@github.com>:

**Comment by brianwrf** [comment]
Which version of Python that you are using?

**Comment by lacroutelacroute** [comment]
on kali linux rolling up to date


~$ sudo pip  list  --format=legacy
beautifulsoup4 (4.5.1)
binwalk (2.1.1)
blist (1.3.6)
Brlapi (0.6.5)
bsddb3 (6.1.0)
chardet (2.3.0)
cracklib (2.9.2)
crcelk (1.1)
cupshelpers (1.0)
cycler (0.10.0)
debtags (2.1)
devscripts (2.16.8)
file-magic (0.3.0)
Forensic1394 (0.1)
GDAL (2.1.2)
gssapi (1.2.0)
hashID (3.1.4)
html5lib (0.999999999)
httplib2 (0.9.2)
hunspell (0.1)
idna (2.1)
ipython (5.1.0)
ipython-genutils (0.1.0)
jpy (0.8.0)
Kyoto-Cabinet (1.5)
llfuse (1.1.1)
louis (3.0.0)
lvm (2.02.167-2-.-2016-11-05-)
mapnik (0.1)
MarkupSafe (0.23)
massweb (0.3.1)
matplotlib (1.5.3)
mysqlclient (1.3.7)
numpy (1.11.2)
onboard (1.3.0)
parsel (1.0.3)
pgmagick (0.6.2)
pickleshare (0.7.4)
Pillow (3.4.2)
pip (9.0.1)
prompt-toolkit (1.0.9)
psycopg2 (2.6.2)
ptyprocess (0.5.1)
PyAudio (0.2.8)
pycparser (2.17)
pycrypto (2.6.1)
pycups (1.9.73)
pycurl (7.43.0)
pyfits (3.4)
Pygments (2.1.3)
pygobject (3.22.0)
pylibacl (0.5.3)
pymad (0.9)
pyodbc (3.0.10)
PyOpenGL (3.1.0)
pyOpenSSL (16.2.0)
pyosmium (2.9.0)
pyparsing (2.1.10)
pyparted (3.10.7)
pyqtgraph (0.10.0)
pyserial (3.2.1)
pySFML (2.2.0)
pysmbc (1.0.15.5)
pytango (9.2.0)
python-apt (1.1.0b5)
python-casacore (2.1.2)
python-debian (0.1.29)
python-librtmp (0.3.0)
python-sane (2.8.2)
PyX (0.14.1)
pyxattr (0.5.6)
pyxdg (0.25)
requests (2.12.1)
rpm-python (4.12.0.2)
scipy (0.18.1)
simplegeneric (0.8.1)
six (1.10.0)
termineter (0.2.6)
traitlets (4.3.1)
unattended-upgrades (0.1)
vboxapi (1.0)
wcwidth (0.1.7)
webencodings (0.5)
wheel (0.29.0)
wheezy.template (0.1.167)
zope.interface (4.3.2)

~$ python -V
Python 2.7.12+


2016-11-26 1:57 GMT+01:00 brianwrf <notifications@github.com>:

**Comment by brianwrf** [comment]
It's weird, I never see this error before. Could you try it on other Linux system(e.g. Ubuntu) rather than Kali?

**Comment by lacroutelacroute** [comment]
I have only 1 system not possible

2016-11-26 16:14 GMT+01:00 brianwrf <notifications@github.com>:

**Comment by brianwrf** [comment]
You can install a virtual machine that have Ubuntu installed.
