### ISSUE TITLE
no module from Crypto.Cipher import AES

### ISSUE THREAD

**Issue by x7peeps** [brianwrf/hackUtils#5]
D:\HackProgram\hackUtils>python hackUtils.py -h
Traceback (most recent call last):
  File "hackUtils.py", line 29, in <module>
    from Crypto.Cipher import AES

**Comment by brianwrf** [comment]
https://www.google.com/search?safe=off&q=ImportError%3A%20No%20module%20named%20Crypto.Cipher&*&cad=h
